#!/usr/bin/env bash
python dna.py databases/small.csv sequences/1.txt
python dna.py databases/small.csv sequences/2.txt
python dna.py databases/small.csv sequences/3.txt
python dna.py databases/small.csv sequences/4.txt
python dna.py databases/large.csv sequences/5.txt
python dna.py databases/large.csv sequences/6.txt
python dna.py databases/large.csv sequences/7.txt
python dna.py databases/large.csv sequences/8.txt
python dna.py databases/large.csv sequences/9.txt
python dna.py databases/large.csv sequences/10.txt
python dna.py databases/large.csv sequences/11.txt
python dna.py databases/large.csv sequences/12.txt
python dna.py databases/large.csv sequences/13.txt
python dna.py databases/large.csv sequences/14.txt
python dna.py databases/large.csv sequences/15.txt
python dna.py databases/large.csv sequences/16.txt
python dna.py databases/large.csv sequences/17.txt
python dna.py databases/large.csv sequences/18.txt
python dna.py databases/large.csv sequences/19.txt
python dna.py databases/large.csv sequences/20.txt
